brew "cask"
brew "mas"
brew "font-meslo-lg-nerd-font"
brew "bat"
brew "fd"
brew "fzf"
brew "fasd"
brew "jq"
brew "mas"
brew "zsh"
brew "neovim"
brew "kubectl"
brew "maven"
brew "gradle"
cask "ngrok"
cask "iterm2"
cask "docker"
cask "gitkraken"
cask "postman"
cask "google-chrome"
cask "intellij-idea"
cask "mysqlworkbench"
mas "Owly", id: 882812218
mas "KakaoTalk", id: 869223134
mas "Slack for Desktop", id: 803453959
